name: Auto Version
inputs:
  token:
    required: true
    description: 'token'
  version:
    required: false
    type: string
    description: 'version'
outputs:
  version:
    description: 'version'
    value: ${{ steps.version.outputs.version }}
runs:
  using: "composite"
  steps:
    - name: Check Input Version
      shell: bash
      id: version
      run: |
        if [[ -z "${{ inputs.version }}" ]]; then
          echo "input_version=true" >> GITHUB_ENV
        else
          echo "version=${{ inputs.version }}" >> $GITHUB_OUTPUT
          echo "input_version=false" >> GITHUB_ENV
        fi
    - name: Running Auto Version
      if: env.input_version == 'false'
      shell: bash
      run: |
        echo $env
        echo "version=auto_v2" >> $GITHUB_OUTPUT
        echo ================++++++=================
        env

