name: Check Version
inputs:
  token:
    required: true
    description: 'token'
  version:
    required: false
    type: string
    description: 'version'
outputs:
  version:
    description: 'version'
    value: ${{ steps.version.outputs.version || inputs.version }}
runs:
  using: "composite"
  steps:
    - name: Run Custom Action
      if: ${{ inputs.version == '' }}
      uses: ./.github/actions/auto-version/
      id: version
      with:
        token: ${{ github.sha }}

