name: Check Version
inputs:
  token:
    required: true
    description: 'token'
  version:
    required: false
    type: string
    description: 'version'
outputs:
  version:
    description: 'version'
    value: ${{ steps.version.outputs.version || steps.auto.outputs.version }}
runs:
  using: "composite"
  steps:
    - name: Check Input Version
      shell: bash
      id: version
      run: |
        if [[ -z "${{ inputs.version }}" ]]; then
          echo "input_version=false" >> GITHUB_ENV
        else
          echo "version=${{ inputs.version }}" >> $GITHUB_OUTPUT
          echo "input_version=true" >> GITHUB_ENV
        fi
    - name: Run Custom Action
      if: ${{ env.input_version == false }}
      uses: ./.github/actions/auto-version/
      id: auto
      with:
        token: ${{ github.sha }}

