name: Use Custom Build Action
on:
  push:
    branches:
      - main
jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: check Dependencies
        run: |
          ls -ali
          pwd
          npm install @actions/core
          npm install @actions/github
          apt install tree -y || true
          tree

      - name: Run Custom Action
        uses: ./.github/actions/check-version/
        id: vs
        with:
          token: ${{ github.sha }}
          version: v1
      - name: Check GITHUB_OUTPUT
        run: | 
          echo ${{ steps.vs.output.version }}
